import type { Metadata } from "next";
import "./globals.scss";
import { AnimatePresence } from "framer-motion";
import { Toaster } from "react-hot-toast";

import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import LenisProvider from "@/view/components/LenisWrapper/LenisWrapper";

config.autoAddCss = false;

export const metadata: Metadata = {
  title: "Thigas.dev",
  description: "Generated by Thiago",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Anton&family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Lora:ital,wght@0,400..700;1,400..700&family=Michroma&family=Montserrat:ital,wght@0,100..900;1,100..900&family=Poppins:ital,wght@0,100..900;1,100..900&family=Roboto+Mono:ital,wght@0,100..700;1,100..700&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon/favicon.ico" type="image/x-icon" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
        ></meta>
      </head>
      <body>
        <LenisProvider>
          <AnimatePresence>{children}</AnimatePresence>
          <Toaster />
        </LenisProvider>
      </body>
    </html>
  );
}
